using System;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Hybrid.Com.SourceGenerator;

public partial class ComGenerator
{
    private static void EmitCoClassSource(SourceProductionContext context, CoClassDefinition classDefinition)
    {
        context.AddSource($"{classDefinition.Type.ToDisplayString()}.g.cs",
            $$"""
              // <auto-generated />
              file sealed unsafe class ComClassInformation : global::System.Runtime.InteropServices.Marshalling.IComExposedClass
              {
                  private static volatile global::System.Runtime.InteropServices.ComWrappers.ComInterfaceEntry* s_vtables;
              
                  public static global::System.Runtime.InteropServices.ComWrappers.ComInterfaceEntry* GetComInterfaceEntries(out int count)
                  {
                      count = {{classDefinition.InterfaceNames.Length}};
                      if (s_vtables == null)
                      {
                          global::System.Runtime.InteropServices.ComWrappers.ComInterfaceEntry* vtables = (global::System.Runtime.InteropServices.ComWrappers.ComInterfaceEntry*)global::System.Runtime.CompilerServices.RuntimeHelpers
                              .AllocateTypeAssociatedMemory(typeof(ComClassInformation), sizeof(global::System.Runtime.InteropServices.ComWrappers.ComInterfaceEntry) * count);
                          global::System.Runtime.InteropServices.Marshalling.IIUnknownDerivedDetails details;
                          {{string.Join(Environment.NewLine, classDefinition.InterfaceNames.Select((name, i) => $$"""
                                details = global::System.Runtime.InteropServices.Marshalling.StrategyBasedComWrappers.DefaultIUnknownInterfaceDetailsStrategy
                                   .GetIUnknownDerivedDetails(typeof({{name}}).TypeHandle);
                                vtables[{{i}}] = new()
                                {
                                    IID = details.Iid,
                                    Vtable = (nint)details.ManagedVirtualMethodTable
                                };
                                """))}}
                                                                                                   
                          s_vtables = vtables;
                      }
                      
                      return s_vtables;
                  }
              }

              namespace {{classDefinition.Type.ContainingNamespace.ToDisplayString()}}
              {
                  [global::System.Runtime.InteropServices.Marshalling.ComExposedClass<ComClassInformation>]
                  public partial class {{classDefinition.Type.Name}}
                  {
                      static {{classDefinition.Type.Name}}()
                      {
                          {{string.Join(Environment.NewLine, classDefinition.InterfaceNames.Select(b =>
                              $"global::Hybrid.Com.TypeLib.HybridTypeLib.Global.RegisterComInterface<{b}, {classDefinition.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();"
                          ))}}
                      }
                  }
              }
              """);
    }
}